/rae:
  ros__parameters:
    camera:
      i_nn_type: none
      i_pipeline_type: RAE
      i_enable_ir: false
      i_enable_imu: false
      # i_external_calibration_path: '/ws/src/rae/rae_bringup/config/cal.json'
    left_front:
      i_resolution: '800'
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 1
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    right_front:
      i_publish_topic: true
      i_output_isp: false
      i_board_socket_id: 2
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    stereo_front:
      i_align_depth: false
    rgb:
      i_output_isp: false
laserscan_kinect:
  ros__parameters:
    # Frame id for the output laserscan.
    output_frame_id: rae_right_front_camera_optical_frame
    # Minimum sensor range (m).
    range_min: 0.4
    # Maximum sensor range (m).
    range_max: 10.0
    # Height of used part of depth img (px).
    scan_height: 50
    # Row step in depth image processing (px).
    depth_img_row_step: 1
    # If continously camera data update.
    cam_model_update: false

    # Height of sensor optical center mount (m).
    sensor_mount_height: 0.8
    # Sensor tilt angle compensation.
    sensor_tilt_angle: -30.0
    # Remove ground from scan.
    ground_remove_en: true
    # Ground margin (m).
    ground_margin: 0.05
    # Sensor tilt angle compensation.
    tilt_compensation_en: true

    publish_dbg_info: true
    threads_num: 1