/rae:
  ros__parameters:
    camera:
      i_nn_type: none
      i_pipeline_type: rae
      i_enable_ir: false
      i_enable_imu: true
      i_calibration_dump: false
      i_pipeline_dump: false
    nn:
      i_nn_config_path: /workspaces/rae_ws/src/rae-ros/rae_camera/config/yolo.json
      i_disable_resize: true
      i_enable_passthrough: true
    rgb:
      i_output_isp: false
      i_set_isp_scale: false
      i_fps: 15.0
      i_preview_size: 416
      i_board_socket_id: 0

    # For rgbd mode
    left:
      i_resolution: '800'
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 1
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    right:
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 2
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    stereo:
      i_align_depth: false
    # For RAE mode
    left_front:
      i_resolution: '800'
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 1
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
      i_preview_size: 416
    right_front:
      i_publish_topic: true
      i_output_isp: false
      i_board_socket_id: 2
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
      i_preview_size: 416
    stereo_front:
      i_align_depth: false
      i_publish_right_rect: false
      i_depth_preset: HIGH_DENSITY
    stereo_back:
      i_align_depth: false
      i_publish_right_rect: false
      i_depth_preset: HIGH_DENSITY
    left_back:
      i_resolution: '800'
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 3
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    right_back:
      i_publish_topic: false
      i_output_isp: false
      i_board_socket_id: 4
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400

    # For CamArray
    a:
      i_output_isp: false
      i_fps: 15.0
      i_preview_size: 416
      i_board_socket_id: 0
    b:
      i_publish_topic: true
      i_output_isp: false
      i_board_socket_id: 1
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    c:
      i_publish_topic: true
      i_output_isp: false
      i_board_socket_id: 2
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    d:
      i_publish_topic: true
      i_output_isp: false
      i_board_socket_id: 3
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    e:
      i_publish_topic: true
      i_output_isp: false
      i_board_socket_id: 4
      i_resolution: '800'
      i_set_isp_scale: false
      i_width: 640
      i_height: 400
    